#!/usr/bin/env ruby

require 'rubygems'
require 'rack'
# $:.unshift File.join(File.dirname(__FILE__), "vendor", "camping", "bin")
Dir.glob(File.join(File.dirname(__FILE__),"/vendor/*")).each do |lib|
  $:.unshift File.join(lib, "lib")
end

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

#gem 'camping', version

load 'vendor/camping/bin/camping'
